  - name: Add secret share
    win_share:
      name: General Share
      description: General Share
      path: E:\shares\general
      list: no
      full: Administrators,rw-test
      read: ro-test
  - name: Add secret share
    win_share:
      name: HR Share
      description: HR Share
      path: E:\shares\hrshare
      list: no
      full: Administrators,rw-test,domain admins
      read: ro-test
