New-ADOrganizationalUnit -Name "PEOPLE" -Path "DC=LAB,DC=LOCAL"
New-ADOrganizationalUnit -Name "EMPLOYEES" -Path "OU=PEOPLE,DC=LAB,DC=LOCAL"
New-ADOrganizationalUnit -Name "VENDORS" -Path "OU=PEOPLE,DC=LAB,DC=LOCAL"
New-ADOrganizationalUnit -Name "DISABLED USERS" -Path "DC=LAB,DC=LOCAL"
New-ADOrganizationalUnit -Name "SERVICE ACCOUNTS" -Path "DC=LAB,DC=LOCAL"
New-ADOrganizationalUnit -Name "GROUPS" -Path "DC=LAB,DC=LOCAL"
New-ADOrganizationalUnit -Name "RESOURCES" -Path "OU=GROUPS,DC=LAB,DC=LOCAL"
New-ADOrganizationalUnit -Name "SECURITY" -Path "OU=GROUPS,DC=LAB,DC=LOCAL"
New-ADOrganizationalUnit -Name "VENDOR GROUPS" -Path "OU=GROUPS,DC=LAB,DC=LOCAL"
New-ADOrganizationalUnit -Name "DEVICES" -Path "DC=LAB,DC=LOCAL"
New-ADOrganizationalUnit -Name "SERVERS" -Path "OU=DEVICES,DC=LAB,DC=LOCAL"
New-ADOrganizationalUnit -Name "WORKSTATIONS" -Path "OU=DEVICES,DC=LAB,DC=LOCAL"
